import '../models/clothing_item.dart';

const List<String> CATEGORIES = [
  "All",
  "Tops",
  "Bottoms",
  "Outerwear",
  "Accessories",
];

final List<ClothingItem> CLOTHING_DATA = [
  ClothingItem(
    id: "0",
    name: "Premium Sweater Pack",
    brand: "AR COLLECTION",
    price: 85.0,
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500",
    category: "Tops",
    isFeatured: true,
    isNew: true,
    rating: 5.0,
    reviewCount: 12,
    sizes: ["M", "L", "XL"],
    description: "A premium 3D sweater pack optimized for AR try-on. Features high-resolution textures and realistic fabric simulation.",
    modelPath: "assets/models/sweater_pack.glb",
    colors: [
      ClothingColor(name: "Cream", hex: "#F5F5DC"),
      ClothingColor(name: "Navy", hex: "#000080"),
    ],
  ),
  ClothingItem(
    id: "1",
    name: "Classic White Tee",
    brand: "ESSENTIALS",
    price: 35.0,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
    category: "Tops",
    isFeatured: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 342,
    sizes: ["S", "M", "L", "XL"],
    description: "The perfect everyday tee made from 100% organic cotton. A slightly relaxed fit with dropped shoulders for maximum comfort and style.",
    modelPath: "assets/models/classic_tee.glb",
    colors: [
      ClothingColor(name: "White", hex: "#FFFFFF"),
      ClothingColor(name: "Black", hex: "#111111"),
      ClothingColor(name: "Heather Gray", hex: "#9CA3AF"),
    ],
  ),
  ClothingItem(
    id: "2",
    name: "Vintage Wash Denim Jacket",
    brand: "LEVI'S",
    price: 120.0,
    image: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=500",
    category: "Outerwear",
    isFeatured: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 1284,
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "The original jean jacket since 1967. A symbol of self-expression for decades, and a great starting point for customization.",
    modelPath: "assets/models/denim_jacket.glb",
    colors: [
      ClothingColor(name: "Vintage Blue", hex: "#5C7CA9"),
      ClothingColor(name: "Black", hex: "#1D1D1D"),
      ClothingColor(name: "Light Blue", hex: "#A8BBE6"),
    ],
  ),
  ClothingItem(
    id: "3",
    name: "Pleated Trousers",
    brand: "AMI PARIS",
    price: 285.0,
    image: "https://images.unsplash.com/photo-1594938384824-03248aa0c3fb?w=500",
    category: "Bottoms",
    isFeatured: false,
    isNew: true,
    rating: 4.6,
    reviewCount: 89,
    sizes: ["28", "30", "32", "34", "36"],
    description: "Classic wool blend pleated trousers with a relaxed, straight-leg crop fit. Features double front pleats and side belt adjusters.",
    modelPath: "assets/models/trousers.glb",
    colors: [
      ClothingColor(name: "Navy", hex: "#1C2A3D"),
      ClothingColor(name: "Camel", hex: "#C5A88B"),
      ClothingColor(name: "Olive", hex: "#4B5320"),
    ],
  ),
  ClothingItem(
    id: "4",
    name: "Ribbed Knit Beanie",
    brand: "CARHARTT WIT",
    price: 28.0,
    image: "https://images.unsplash.com/photo-1576878950153-f8ed691ee6e1?w=500",
    category: "Accessories",
    isFeatured: false,
    isNew: false,
    rating: 4.9,
    reviewCount: 4531,
    sizes: ["OS"],
    description: "A thick, warm acrylic knit hat featuring the iconic square woven label on the front cuff. Stretchy, one-size-fits-all design.",
    modelPath: "assets/models/beanie.glb",
    colors: [
      ClothingColor(name: "Hamilton Brown", hex: "#A87042"),
      ClothingColor(name: "Black", hex: "#111111"),
      ClothingColor(name: "Dark Navy", hex: "#101B2E"),
    ],
  ),
];
